#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gres=gpu:1 
#SBATCH --cpus-per-task=16
#SBATCH --time=02:30:00
#SBATCH -A ziran-n
#SBATCH -J e2e_train

module purge
module load anaconda
module load cuda
module load cudnn
module load use.own
module list

/home/mgagvani/.conda/envs/e2e_proj/bin/python --version

echo $PYTHONPATH
cd $SLURM_SUBMIT_DIR

date
/home/mgagvani/.conda/envs/e2e_proj/bin/python train.py dk
date